baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Codon Docs'
theme="hugo-book"
enableEmoji = true
[markup]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]